
---

- name: download the nginx rpm file
  get_url:
    url: http://nginx.org/packages/centos/7/x86_64/RPMS/nginx-1.12.2-1.el7_4.ngx.x86_64.rpm
    dest: /opt/dockerize/
    mode: 0755
  tags:
     - nginx_install

- name: install the rpm package
  command: 'yum -y localinstall /opt/dockerize/nginx-1.12.2-1.el7_4.ngx.x86_64.rpm'
  changed_when: False
  register: nginx_version

- name: Configure nginx webserver
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0755

- name: Reload nginx
  service: name=nginx state=reloaded

- name: Restart nginx
  service: name=nginx state=restarted

- name: stop firewalld
  service: name=firewalld state=stopped
